name: flutter_flash_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  cloud_firestore: ^4.4.2
  firebase_auth: ^4.2.8
  firebase_core: ^2.6.1
  flutter:
    sdk: flutter
  modal_progress_hud_nsn: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
